DROP TABLE IF EXISTS detalle_venta;
DROP TABLE IF EXISTS pago;

DROP TABLE IF EXISTS venta;
DROP TABLE IF EXISTS reporte;
DROP TABLE IF EXISTS asistencia;
DROP TABLE IF EXISTS membresias;

DROP TABLE IF EXISTS producto;
DROP TABLE IF EXISTS socios;
DROP TABLE IF EXISTS usuarios;
